# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/myexample
      username: root
      password: 123321
      driver-class-name: com.mysql.cj.jdbc.Driver
